/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package war;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JFrame;

/**
 *
 * @author msndo
 */
public class Atacar_Dialog extends JDialog implements ActionListener {

        private MapView map;
        private Controller controller;
        private List<Territory> alvos;
        List<Integer> alvosIndice;
        
    public Atacar_Dialog(MapView map) {
        controller = Controller.getInstance();
        alvosIndice = new ArrayList<>();
        this.map=map;
	setBounds(550, 300, 618, 330);
	getContentPane().setLayout(null);                
        
        initComponents();
        
                // ---- Acessa nome do País e numero de tropas
        nomePaísrLabel.setText(controller.getTerritory(map.getIndice()).getName());
        numeroTropasLabel.setText(Integer.toString(controller.getTerritory(map.getIndice()).getTroops()));
        // -----------------
        
        constroiAlvos();
        System.out.println("AQUI ?");
        atacarButton.addActionListener(this);
        faseEndButton.addActionListener(this);

                
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        jogadorLabel = new javax.swing.JLabel();
        tropasLabel = new javax.swing.JLabel();
        nomePaísrLabel = new javax.swing.JLabel();
        numeroTropasLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        atacarButton = new javax.swing.JButton();
        faseEndButton = new javax.swing.JButton();
        alvosCombox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        qtdTextField = new javax.swing.JTextField();
        mensagemLabel = new javax.swing.JLabel();

        jTextField2.setText("jTextField2");

        jTextField3.setText("jTextField3");

        jScrollPane1.setViewportView(jTextPane1);

        jLabel2.setText("jLabel2");

        jogadorLabel.setText("País:");

        tropasLabel.setText("Tropas no Território :");

        jLabel3.setText("Atacar Território :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ATAQUE A TERRITÓRIO INIMIGO");

        atacarButton.setText("Atacar");

        faseEndButton.setText("Encerrar Fase");

        alvosCombox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        alvosCombox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alvosComboxActionPerformed(evt);
            }
        });

        jLabel1.setText("QTD de Tropas :");

        qtdTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtdTextFieldActionPerformed(evt);
            }
        });

        mensagemLabel.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        mensagemLabel.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(qtdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(atacarButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(faseEndButton, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jogadorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomePaísrLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(101, 101, 101))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tropasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numeroTropasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(alvosCombox, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(58, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(mensagemLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jogadorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomePaísrLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tropasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numeroTropasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alvosCombox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(qtdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(atacarButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mensagemLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(faseEndButton)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alvosComboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alvosComboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alvosComboxActionPerformed

    private void qtdTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtdTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtdTextFieldActionPerformed
//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> alvosCombox;
    private javax.swing.JButton atacarButton;
    private javax.swing.JButton faseEndButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel jogadorLabel;
    private javax.swing.JLabel mensagemLabel;
    private javax.swing.JLabel nomePaísrLabel;
    private javax.swing.JLabel numeroTropasLabel;
    private javax.swing.JTextField qtdTextField;
    private javax.swing.JLabel tropasLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void dispose() {
    this.map.setPressed(false);
    super.dispose();
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        Object obj = e.getSource();
        if ( obj == atacarButton ) {
            Boolean deuErro = validaCampo();
            int qtd = Integer.parseInt(qtdTextField.getText());
            if(deuErro == false){
            int um_alvo = alvosCombox.getSelectedIndex();
            int um_alvo_real = alvosIndice.get(um_alvo);
            Territory[] winners = controller.battle(map.getIndice(), qtd , um_alvo_real);
            //Winners_Dialog dialog = new Winners_Dialog(winners);
            //dialog.setVisible(true);
            
            numeroTropasLabel.setText(Integer.toString(controller.getTerritory(map.getIndice()).getTroops()));
            this.dispose();
            }
        }
        
        if ( obj == faseEndButton ) {
        controller.changeState();
        this.dispose();
        
        }
    }
   



    private void constroiAlvos() {
        alvosCombox.removeAllItems();
        alvos = controller.elegerAlvos(map.getIndice());
        
        for (int i = 0; i < alvos.size(); i++) {
        alvosCombox.addItem( alvos.get(i).getName() );
        alvosIndice.add( alvos.get(i).getID() );
            System.out.println(alvos.get(i).getID());
            
        }

     }
    
        private boolean validaCampo() {
	boolean deuErro = false;
        
        


            if (qtdTextField.getText().trim().length() == 0) {
                deuErro = true;
                mensagemLabel.setText("Campo de preenchimento obrigatório");
            } 
            else {
                mensagemLabel.setText("");
                
                
                int qtd = Integer.parseInt(qtdTextField.getText());
                System.out.println(qtdTextField.getText());

                if( qtd < 1 || qtd > ( Integer.parseInt( numeroTropasLabel.getText()) - 1 ) ) {
                    deuErro = true;
                    mensagemLabel.setText("Não é possivel atacar com este numero de tropas");

                }

                else {
                    mensagemLabel.setText("");
                
                
                    if( qtd > 3 ) {
                        deuErro = true;
                        mensagemLabel.setText("Você só pode atacar com no maximo 3 tropas");

                    }

                    else {
                        mensagemLabel.setText("");
                    }
                
                }
                
            }
            
    return deuErro;
    }
        
}

